name: movies
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # UI & Animations
  cupertino_icons: ^1.0.2
  lottie: ^3.3.2
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  curved_navigation_bar: ^1.0.3
  flutter_dotenv: ^6.0.0
  youtube_player_iframe: ^5.2.2
  webview_flutter: ^4.8.0
  cached_network_image: ^3.3.1
  # State Management & Storage
  get: ^4.6.7
  get_storage: ^2.1.1

  # Networking & APIs
  http: ^1.1.0
  url_launcher: ^6.3.2

  # Video
  youtube_player_flutter: ^9.1.3

  # Authentication
  google_sign_in: ^7.2.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.2
  firebase_messaging: ^16.0.4

  # Notifications
  awesome_notifications: ^0.10.1
  path_provider: ^2.1.5

  # WebView
  flutter_inappwebview: ^6.1.0

  # Windows support
  win32: ^5.1.0

  # Rating
  rate: ^0.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_animate: ^4.5.2
  sqflite_common_ffi: ^2.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.jpg
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/animations/
  - .env

  fonts:
  - family: Cairo
    fonts:
    - asset: assets/font/Cairo-Regular.ttf
